Use PyJWT instead of python-jose
intuit/oauth-pythonclient pull request #49
Opened 2024-05-28 12:33 UTC by Natim

Alternate to https://github.com/intuit/oauth-pythonclient/pull/48/files

2024-06-10 08:35 UTC, Natim commented
![image](https://github.com/intuit/oauth-pythonclient/assets/229453/d9585600-a72e-4d35-9f39-7cd54ef8095d)

2024-06-27 11:06 UTC, yahel2410 approved these changes
LGTM

2024-07-01 08:55 UTC, Natim commented
@yahel2410 what's next? Can we merge?

2024-07-09 02:03 UTC, robert-mings commented
Hi @Natim,

Thanks for this contribution! The move away from python-jose is a much needed change.

From my testing, I had a few questions/asks:
- It looks like the cryptography backend was being supplied as a `python-jose` dependency. I needed to install the [cryptography package](https://cryptography.io/en/latest/) directly. Was this the same in your testing? If so, we'll need to add this as a dependency.
- [Line 169](https://github.com/intuit/oauth-pythonclient/pull/49/files#diff-cde246b26833c4c8d5c6aff45d668cdc5ac1bb308b6ec56c6aca9a63334ac873R169) - I believe the `verify` method will need to be changed as it was previously supplied by `python-jose`.
- Do you mind adding versioning for [PyJWT](https://github.com/intuit/oauth-pythonclient/pull/49/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R10)?

2024-07-09 05:51 UTC, Natim commented
Hello Robert, no need for the cryptography package anymore with PyJWT.

As for the verify method, PyJWT provides the same method/API. The code is tested and we have been using it in production for more than a month.

In the Python dependencies philosophy, libraries should not enforce dependencies versioning so that project can handle it without library version conflicts.

This is because you can't use two different version of a lib in the same project.

2024-07-09 17:09 UTC, Natim commented
> Do you mind adding versioning for [PyJWT](https://github.com/intuit/oauth-pythonclient/pull/49/files#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R10)?

Done, thanks

2024-07-09 17:12 UTC, robert-mings commented
Thanks @Natim. Great to hear you've been using this in production.

- RE: cryptography - [Based on the PyJWT docs](https://pyjwt.readthedocs.io/en/stable/installation.html#cryptographic-dependencies-optional), the RSA algorithm isn't supported by default until you install the cryptography package. Is there any chance this was being supplied as a dependency from another package in your build? In an isolated environment, I'm receiving exceptions until this is explicitly installed.
- RE: verify method - Can you shared more information on this? I'm not seeing anywhere in the docs where it talks about a verify method/API.
- RE: package versions - Lower bounds look good, thanks for adding this.

2024-07-09 17:22 UTC, Natim commented
> cryptography - [Based on the PyJWT docs](https://pyjwt.readthedocs.io/en/stable/installation.html#cryptographic-dependencies-optional), the RSA algorithm isn't supported by default until you install the cryptography package. Is there any chance this was being supplied as a dependency from another package in your build? In an isolated environment, I'm receiving exceptions until this is explicitly installed.

Ok then, let's add it :pray:

2024-07-09 17:26 UTC, Natim commented
> verify method - Can you shared more information on this? I'm not seeing anywhere in the docs where it talks about a verify method/API.

It's part of the PyJWK Algorithm API: https://github.com/jpadilla/pyjwt/blob/527fec277e8215a197f8facd3778b359043704ef/jwt/algorithms.py#L180-L185

2024-07-09 21:50 UTC, jordan-chalupka approved these changes

2024-07-14 06:55 UTC, yahel2410 commented
Can you please proceed and merge this?

2024-07-18 01:08 UTC, keaton185 commented
@robert-mings are we any closer to being able to merge this one?

2024-07-19 21:38 UTC, robert-mings commented
@Natim, @keaton185, @yahel2410 - We're close but I have yet to get this working as it's currently written. Facing `AttributeError: 'PyJWK' object has no attribute 'verify'`. I don't believe it's a namespace issue either as `jwt` is uninstalled.

Can I confirm if others are using this successfully as is?

2024-07-19 22:34 UTC, Natim commented
Can you write a test for it I can look at?
It supposed to be an Algorithm object not a JWK object that you use to
verify.

2024-07-21 07:19 UTC, Natim commented on intuitlib/utils.py
> +    return PyJWKSet.from_dict(data)[kid]
`PyJWKSet[kid]` returns an Algorithm object: https://github.com/jpadilla/pyjwt/blob/master/jwt/api_jwk.py#L131

2024-07-21 07:20 UTC, Natim commented on intuitlib/utils.py
> +    public_key = get_jwk(id_token_header['kid'], jwk_uri)
```suggestion
    public_key = get_jwk(id_token_header['kid'], jwk_uri).key
```

2024-07-21 07:21 UTC, Natim commented on intuitlib/utils.py
> +    public_key = get_jwk(id_token_header['kid'], jwk_uri).key
`PyJWK.key` returns an algorithm

2024-07-21 07:22 UTC, Natim commented
@robert-mings can you try again, you were right. I believe we are missing a test for this part of the lib, I was expecting it to exist which I was wrong. The good news is that our production code doesn't seem to use this part of the code.

2024-07-27 00:05 UTC, robert-mings commented
Thanks @Natim for adding this. Just an update from my side - this solved the `AttributeError`, however, this introduced a a number of additional errors.

Looks like we needed two additional arguments - padding and algorithm. Easy enough, passing those solves that error:
`is_signature_valid = public_key.verify(message.encode('utf-8'), id_token_signature, algorithm='RS256', padding='PKCS1v15')`

That then runs into another error: `TypeError: Expected instance of hashes.HashAlgorithm`

I'm almost thinking we can simplify and use the `decode` method since this already incorporates logic for validating the signature. This would also allow a bit of cleanup. Maybe something like:

```
   try:
        public_key = get_jwk(id_token_header['kid'], jwk_uri).key
        jwt.decode(id_token, public_key, audience=client_id, algorithms=['RS256'])
        return True
    except:
        return False
```

Thoughts?

2024-07-28 17:30 UTC, Natim commented
@robert-mings can you try again like that?

2024-07-29 21:52 UTC, robert-mings requested changes
Awesome @Natim - this looks good. Only required change is to `import jwt` since we are using the decode api directly (as well as the 2 required references).

I added a couple lines of cleanup as well. Let me know if you're able to make these changes, otherwise I can get this merged and follow-up directly after.

2024-07-29 21:52 UTC, robert-mings commented on intuitlib/utils.py
> +from jwt import PyJWKSet, PyJWTError
Since we are using the `decode` api, let's `import jwt`.

2024-07-29 21:52 UTC, robert-mings commented on intuitlib/utils.py
> +    except PyJWTError:
`jwt.PyJWTError`

2024-07-29 21:52 UTC, robert-mings commented on intuitlib/utils.py
>      message = id_token_parts[0] + '.' + id_token_parts[1]
Can remove the following as they are no longer used:

- `id_token_signature = urlsafe_b64decode(((_correct_padding(id_token_parts[2])).encode('ascii')))`
- `message = id_token_parts[0] + '.' + id_token_parts[1]`

2024-07-29 21:52 UTC, robert-mings commented on intuitlib/utils.py
> +    return PyJWKSet.from_dict(data)[kid]
`jwt.PyJWKSet.from_dict(data)[kid]`

2024-07-31 02:20 UTC, robert-mings approved these changes
Looks great. Thanks again for the contribution @Natim.

Merging now and will get a new version released.

2024-07-31 02:22 UTC, merged